name = "akasha-subscriber"
account_id = "54211bf1c63ae3a5729dabd4bf94aa2b"
main = "build/worker/shim.mjs"
send_metrics = false
compatibility_date = "2024-10-01"
workers_dev = false
routes = [{ pattern = "rust.hellotime.de5.net", custom_domain = true }]
[build]
command = "worker-build --release"
