name = "akasha-subscriber"
main = "build/worker/shim.mjs"
send_metrics = false
compatibility_date = "2024-10-01"
workers_dev = false
routes = [{ pattern = "rust.hellotime.de5.net/*", zone_name = "hellotime.de5.net" }]
[build]
command = "worker-build --release"
